/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.9.0
 *
 * Project: 'Blank.Debug+HT32F12366' 
 * Target:  'Debug+HT32F12366' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ht32f1xxxx_01.h"



#endif /* RTE_COMPONENTS_H */
